name: Publish Packages

on:
  workflow_dispatch:
    inputs:
      component:
        required: true
        type: choice
        options:
          - verifier
          - libverifier
  workflow_call:
    inputs:
      component:
        required: true
        type: string

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Enable Node.js corepack
        run: corepack enable

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: pnpm
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        if: ${{ inputs.component == 'libverifier' }}
        with:
          pattern: build-lib-*
          merge-multiple: true
          path: ./packages/

      - name: Publish to NPM
        run: |
          cp $NPM_CONFIG_USERCONFIG .npmrc
          pnpm publish:${{inputs.component}} ${{ github.event_name == 'workflow_dispatch' && '--dry-run' || '' }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - run: pnpm pack:libverifier
        if: ${{ inputs.component == 'libverifier' && github.event_name == 'workflow_dispatch' }}

      - uses: actions/upload-artifact@v4
        if: ${{ inputs.component == 'libverifier' && github.event_name == 'workflow_dispatch' }}
        with:
          name: dist-libs
          path: dist/
