name: release-please

on:
  push:
    branches:
      - master

jobs:
  release-please:
    permissions:
      contents: write
      pull-requests: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Run release-please
        uses: GoogleCloudPlatform/release-please-action@v4
        id: release
        continue-on-error: true
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
